* bumpve
CORE
PRE-RELEASE
BUILD

Each of the constituent parts shall be labeled henceforth as *element* and
collectively as the *elements*.

Each of the elements is identified by their respective *${ELEMENT}_RE*

An element is further broken down into *identifers*.

The CORE element's form is fixed as per the specification to:
x.y.z
Where [ x, y, z ] are each numbers of any length without leading 0's.

The PRE-RELEASE element's form is not fixed as per the specification. It only
imposes limits on the available characters.

** Options
-a --auto
shall append missing element and identifiers as neccessary if the target element
is missing.
** stitch identifier
Should stitch only the identifier being bumped.
** stitch leading identifiers
Should stitch the identifiers up to and including the one being bumped.
** stitch element
Should stitch the whole element
** stitch trailing
Should stitch trailing identifiers across element boundaries up to and including
the one being bumped.
** stitch semver
** stitch all
